[workspace]
resolver = "2"
members = [
    "crates/darksouls3",
    "crates/sekiro",
    "crates/shared",
]

[workspace.package]
version = "0.2.0"
edition = "2024"
repository = "https://github.com/nex3/fromsoftware-extra"
license = "MIT OR Apache-2.0"

[workspace.dependencies]
fromsoftware-shared = { git = "https://github.com/vswarte/fromsoftware-rs" }
fromsoftware-extra-shared = { path = "crates/shared" }
bitflags = "2.11.0"
thiserror = "1"
pelite = "0.10"
ilhook = { version = "2.2.0", features = ["x64"] }
log = "0.4.29"

[workspace.dependencies.windows]
version = "0.54"
features = [
    "Win32_Foundation",
    "Win32_System_LibraryLoader",
]

[profile.release]
strip = true
lto = true
codegen-units = 1
panic = "abort"
opt-level = "z"
